const BASE_URL = `${process.env.REACT_APP_BASE_URL}`
console.log(BASE_URL,"base_url")

export const Config = {
    Signup_url: `${BASE_URL}signup`,
    Login_url: `${BASE_URL}login`,
    DistributorRequest_url: `${BASE_URL}distributorRequest`,
    Get_Banner_url: `${BASE_URL}banner/get-banners`,
    Get_Categories: `${BASE_URL}category/get-category`,
    Get_Products: `${BASE_URL}product/get-products`,
    Get_Product_Details: `${BASE_URL}product/get-product-details`,
    Add_to_cart: `${BASE_URL}cart/add-item`,
    decrease_item: `${BASE_URL}cart/decrease-quanity`,
    get_cart_items: `${BASE_URL}cart`,
    remove_cart_item: `${BASE_URL}cart/remove-all-items`,
    // get_product_by_categories: `${BASE_URL}product/get-products-by-category`,
    get_product_by_categories: `${BASE_URL}products`,
    add_delivery_address: `${BASE_URL}api/saveDeliveryAddress`,
    get_order_summary: `${BASE_URL}api/Order-summary`,
    update_delivery_address: `${BASE_URL}api/updateAddress`,
    get_delivery_address: `${BASE_URL}api/getAddress`,
    get_city_state_from_pincode: `${BASE_URL}getstatecity`,
    create_order: `${BASE_URL}api/create-order`,
    verifyPayment: `${BASE_URL}api/verify-payment`,
    place_order: `${BASE_URL}api/place-order`,
    order_details_by_id: `${BASE_URL}api/order-details`,
    get_order_history: `${BASE_URL}api/order-history`,
    search_products: `${BASE_URL}api/search`,
    rate_product: `${BASE_URL}rate-product`,
    get_home_categories: `${BASE_URL}home/categories`,
    get_menu: `${BASE_URL}get-menu`,
    get_products_by_home_category: `${BASE_URL}home`,
    get_best_selling_products: `${BASE_URL}products/best-selling`,
    get_new_arrivals: `${BASE_URL}products/new-arrivals`,
    contact_us: `${BASE_URL}api/contact`
}